import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import MobileFooter from "@/components/MobileFooter";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Saymee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >
        <Header />
        {children}
        <Footer />
        <MobileFooter />
      </body>
    </html>
  );
}
